name: Linear Regression CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python src/train.py

    - name: Quantize Model
      run: |
        python src/quantize.py

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOC_PASSWORD }}" | docker login -u "${{ secrets.DOC_USER }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOC_USER }}/mlopsfinal:v1 .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOC_USER }}/mlopsfinal:v1

    - name: Run Docker Container (Inference)
      run: |
        docker run --rm ${{ secrets.DOC_USER }}/mlopsfinal:v1 python src/inference.py
