name: MLOps Housing CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-suite:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest src/test_model.py


  train-and-quantize:
    name: Train & Quantize Model
    runs-on: ubuntu-latest
    needs: test-suite

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train Model
        run: python src/train.py

      - name: Quantize Model
        run: python src/quantize.py

      - name: Upload Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-files
          path: model/


  build-and-test-container:
    name: Build & Test Docker Container
    runs-on: ubuntu-latest
    needs: train-and-quantize

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Model Artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-files
          path: model/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOC_PASSWORD }}" | docker login -u "${{ secrets.DOC_USER }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOC_USER }}/mlopsfinal:v1 .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOC_USER }}/mlopsfinal:v1

      - name: Run Inference Inside Container
        run: docker run --rm ${{ secrets.DOC_USER }}/mlopsfinal:v1 python src/inference.py
